### ISSUE TITLE
Issue with Gem Installation

### ISSUE THREAD

**Issue by KagemniKarimu** [nodanaonlyzuul/asciiart#13]
Receive the following error... 

> ERROR:  Error installing asciiart:
>         ERROR: Failed to build gem native extension.
> 
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.

When I check the mkfile log I get  the following:

> assert_minimum_ruby_version!: checking for Ruby version >= 2.3.0... -------------------- yes
> 
> --------------------
> 
> find_executable: checking for magick... -------------------- no
> 
> --------------------
> 
> find_executable: checking for identify... -------------------- no
> 
> --------------------

**Comment by KagemniKarimu** [comment]
I installed ImageMagick with C libraries but retain the same error.

**Comment by nodanaonlyzuul** [comment]
Hi @KagemniKarimu 

Thanks for the bug report.
Can you provide....

1.  asciiart version.
2. Ruby version.
3. Imagemagick version (`convert -version`).
4. OS & OS Version

**Comment by KagemniKarimu** [comment]
Ruby 3.1.0
asciiart Version 0.2.0
Imagemagick 7.1.0 Q16 HDRI-x64
RubyMine 2021.2.3

**Update** FWIW I was able to get (aspects) of it working, so long as I didn't use bundler/make a Gemfile

**Comment by nodanaonlyzuul** [comment]
Hi @KagemniKarimu 

Thanks - FWIW I was able to re-create not being able to install using Ruby 3.1.0.
My specs were:

* Mac OS 11.6 (big sur).
* Ruby 3.1.0
* asciiart 0.2.0
* ImageMagick 7.1.0-22 Q16-HDRI x86_64 2022-01-29

My output is:

```
ERROR:  Error installing asciiart:
	ERROR: Failed to build gem native extension.

    current directory: ~.rvm/gems/ruby-3.1.0/gems/rmagick-4.1.2/ext/RMagick
~.rvm/rubies/ruby-3.1.0/bin/ruby -I /Users/stephenschor/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0 -r ./siteconf20220202-97075-txmvnb.rb extconf.rb
checking for brew... yes
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes
checking for __GNUC__... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

## However

I WAS able to install the gem in Ruby 3.0.0!
@KagemniKarimu  - can you do me a favor and try to install this in Ruby 3.0?
I don't have a Windows machine - and I suspect this is a matter of me needing to bump my rmagick dependency.

Thanks!

**Comment by nodanaonlyzuul** [comment]
Hi @KagemniKarimu 

I have a branch that fixes installation problems in ruby 3.1.0 for me. (while not breaking 3.0 & 2.7).
If you get a moment can you try the following in Ruby 3.1.0?

1.  Pull & checkout the `update/fix-for-ruby3-1` branch.
2. (Using ruby 3.1.0) `bundle install` in the directory.
3.  `gem build asciiart.gemspec`
4.  `gem install asciiart-0.3.0.gem`

This SHOULD build for you. It built for me ....but like I said, I don't have a Windows machine to test on.

**Comment by KagemniKarimu** [comment]
I tried the new branch and it seemed to be working! **Thank you!!!**

**Comment by nodanaonlyzuul** [comment]
Hey Great!

I appreciate you taking the time to test.
I'm going to close this issue, and merge & deploy the new version later.

Thanks for the report.
